language: python
sudo: false
python:
    - "2.7"
install:
    - pip install tox
script:
    - tox
env:
    - TOXENV=py27_dj18_django_jinja
    - TOXENV=py34_dj18_django_jinja
    - TOXENV=py35_dj18_django_jinja
    - TOXENV=py36_dj18_django_jinja
